imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.service_images: 'uploads/images/services'

framework:
    #esi: ~
    translator: { fallbacks: [fr] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

easy_admin:
    entities:
        Services:
            class: AppBundle\Entity\Services
            list:
                fields:
                    - { property: 'title', type: 'string' }
                    - { property: 'description', type: 'string' }
                    - { property: 'image', type: 'image', base_path: '%app.path.service_images%' }
            show:
                fields:
                    - { property: 'title', type: 'string' }
                    - { property: 'description', type: 'string' }
                    - { property: 'image', type: 'image', base_path: '%app.path.service_images%' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'description' }
                    - { property: 'imageFile', type: 'file' }
        Site:
            class: AppBundle\Entity\Site
            form:
                fields:
                    - { property: 'isOpen' }
                    - { property: 'schedule', type: 'ckeditor' }
        Tariffs:
            class: AppBundle\Entity\Tariffs
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'description', type: 'ckeditor' }
        Contact:
            class: AppBundle\Entity\Contact
            list:
                actions: ['-edit', 'show']
            show:
                fields:
                    - { property: 'name' }
                    - { property: 'email' }
                    - { property: 'object' }
                    - { property: 'message' }




vich_uploader:
    db_driver: orm
    mappings:
        service_images:
            uri_prefix:         '%app.path.service_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/services'

ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            toolbar: full